name: Fetch changelogs
on:
  push:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch sitemap
        run: |
          # Bypass bot block with user agent hack. Basic but works most the time
          wget -U "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" https://feedback.minecraft.net/hc/sitemap.xml > sitemap.xml
          
      - name: Fetch articles
        run: |
          for a in `grep -E "preview"`
          do
            echo $a
          done
